
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - coffees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - coffees/finalizers
  verbs:
  - update
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - coffees/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - teas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - teas/finalizers
  verbs:
  - update
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - teas/status
  verbs:
  - get
  - patch
  - update
