# permissions for end users to view teas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tea-viewer-role
rules:
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - teas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hotdrink.slashpai.github.io
  resources:
  - teas/status
  verbs:
  - get
