apiVersion: hotdrink.slashpai.github.io/v1alpha1
kind: Tea
metadata:
  name: black-tea
spec:
  # Add fields here
  sugar: false
  type: black

---
apiVersion: hotdrink.slashpai.github.io/v1alpha1
kind: Tea
metadata:
  name: milk-tea
spec:
  # Add fields here
  sugar: true
  type: milk
