apiVersion: hotdrink.slashpai.github.io/v1alpha1
kind: Tea
metadata:
  name: black-tea
spec:
  # Add fields here
  sugar: false
  type: black
  recipe: "echo make black tea without sugar"

---
apiVersion: hotdrink.slashpai.github.io/v1alpha1
kind: Tea
metadata:
  name: milk-tea
spec:
  # Add fields here
  sugar: true
  type: milk
  recipe: "echo make milk tea with sugar"
---
apiVersion: hotdrink.slashpai.github.io/v1alpha1
kind: Tea
metadata:
  name: milk-tea-no-sugar
spec:
  # Add fields here
  sugar: false
  type: milk
  recipe: "echo make milk tea without sugar"